version: '3'

services:
  bedrock_server:
    image: bedrock_server:latest
    container_name: bedrock_server
    environment:
      - BEDROCK_DOWNLOAD_ZIP=PARAM_BEDROCK_URL
    ports: 
      - 19132:19132/udp
    stdin_open: true
    tty: true
  volumes:
    - PARAM_HOME/worlds:/home/bedrock/bedrock_server/worlds
    - PARAM_HOME/server.properties:/home/bedrock/bedrock_server/server.properties
    - PARAM_HOME/permissions.json:/home/bedrock/bedrock_server/permissions.json
    - PARAM_HOME/whitelist.json:/home/bedrock/bedrock_server/whitelist.json
