version: '3'

services:
  bedrock_server:
    image: PARAM_SERVER_NAME:latest
    build: .
    container_name: PARAM_SERVER_NAME
    ports: 
      - PARAM_PORT4:19132/udp
      - PARAM_PORT6:19133/udp
    stdin_open: true
    tty: true
    volumes:
      # temporarily we are mapping the worlds folder to an import folder because when
      # mounting this volume in Windows at least the bedrock server crashes.
      - PARAM_HOME/worlds:/home/bedrock/bedrock_server/import/worlds
      - PARAM_HOME/config:/home/bedrock/bedrock_server/config

    # override the default entrypoint to include access to a bash terminal for debugging.
    entrypoint: bash -c "/home/bedrock/startup.sh && /bin/bash"
