version: '3'

services:
  bedrock_server:
    image: bedrock_server:latest
    container_name: bedrock_server
    environment:
      - BEDROCK_DOWNLOAD_ZIP=PARAM_BEDROCK_URL
    ports: 
      - 19132:19132/udp
    stdin_open: true
    tty: true
    volumes:
      - ./data/worlds:PARAM_WORDLS
      - ./data/server.properties:PARAM_CONFIG/server.properties
      - ./data/permissions.json:PARAM_CONFIG/permissions.json
      - ./data/whitelist.json:PARAM_CONFIG/whitelist.json
